name: Learning GitHub Actions
run-name: Learning github actions !!
on: [push]
jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Define variable
        run: echo "USERNAME=${{ github.actor }}" >> $GITHUB_ENV
      - name: Run script
        run: python hello-world.py

